name: Generate Web Site
on:
    push:
        branches:
        - main
    pull_request:

jobs:
    generator:
        name: Generator
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: '3.10'
        -   name: "Main Script"
            run: |
                sudo apt update
                sudo apt install graphicsmagick

                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt
                make

                if test "$GITHUB_REF" == "refs/heads/main"; then
                    eval $(ssh-agent)
                   echo "$GH_PAGES_AUTOPUSH_KEY" | ssh-add -

                   git config --global user.email "andreask@illinois.edu"
                   git config --global user.name "GH Pages Autopusher"

                   make publish
                fi
            env:
                GH_PAGES_AUTOPUSH_KEY: ${{ secrets.GH_PAGES_AUTOPUSH_KEY }}
